//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Crud_Entity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        public int ID { get; set; }
        [Required (ErrorMessage ="Name field is required")]
        [StringLength(40,ErrorMessage ="Name cannot exied 40 characters ")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Phone Number field is required")]
        [RegularExpression(@"^[6-9]\d{9}$", ErrorMessage = "Enter valid 10-digit Indian mobile")]
        public Nullable<long> PhoneNumber { get; set; }
        [Required(ErrorMessage = "Gmail field is required")]
        [EmailAddress(ErrorMessage ="Enter a valid email address")]
        public string Gmail { get; set; }
        [Required(ErrorMessage = "Password field is required")]
        [StringLength(20,MinimumLength =6, ErrorMessage ="Min Length is 6 & max length  is 20")]
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Roles_Table Roles_Table { get; set; }
    }
}
