//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Crud_Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string User1 { get; set; }
        public Nullable<int> Role_id { get; set; }
        public string password { get; set; }
    
        public virtual Roles_Table Roles_Table { get; set; }
    }
}
